// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd6qun1niuX1HZ_ECq2CB0fVAuVA0qXFk',
    appId: '1:138435619194:web:6379527fc8633411bf8ec3',
    messagingSenderId: '138435619194',
    projectId: 'todo-list-app-8d8db',
    authDomain: 'todo-list-app-8d8db.firebaseapp.com',
    storageBucket: 'todo-list-app-8d8db.appspot.com',
    measurementId: 'G-L47B8MSYRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvzG5HaqS5FSHKTJ02N_kxrFuwe4_3kXc',
    appId: '1:138435619194:android:f1c205376e093df7bf8ec3',
    messagingSenderId: '138435619194',
    projectId: 'todo-list-app-8d8db',
    storageBucket: 'todo-list-app-8d8db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM6BYxQ3eH5l8keQMBeGIQ0s8wKLAmz-I',
    appId: '1:138435619194:ios:f390b4ab86bf624abf8ec3',
    messagingSenderId: '138435619194',
    projectId: 'todo-list-app-8d8db',
    storageBucket: 'todo-list-app-8d8db.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );
}
